"""U100/R8: a state driver that plays real cg.api games toward specific mechanics.

Key characterized facts about the engine (discovered via the _probe*.py scratch
probes and verified against many real replay-derived games; see LOOP_BRIEF.md
U100 status and docs/rules_as_implemented.md for the write-up):

1. ``search_begin`` MUST be called with a real ``Observation`` extracted from a
   recorded replay (its ``search_begin_input`` token is generated by the native
   engine and cannot be fabricated). Once such an observation is supplied, the
   engine reconstructs the TRUE hidden game state that produced it -- the
   ``your_deck``/``opponent_deck`` arguments are only used for cards whose
   identity is not already fixed by the replay (``Observation.select.deck``
   is populated for these mid-game snapshots, and the docstring for
   ``search_begin`` says the deck argument is ignored whenever that is the
   case). Concretely: the active/bench Pokemon you get are whatever the real
   replay's match actually had, regardless of what deck lists you pass. This
   means characterizing mechanics that need a *specific* card (a particular
   weakness/resistance pairing, a status-inducing attack) is a MINING problem,
   not a deck-construction problem: scan many replay-derived games with a
   policy that prefers to attack/develop the board, and harvest the mechanic
   from whatever naturally occurs.

2. ``search_step`` returns a NEW ``searchId`` on every call
   (``SearchState.searchId``). The caller MUST carry it forward
   (``sid = new.searchId``); reusing the original root ``searchId`` silently
   replays the SAME decision over and over without ever advancing the game.
   This was the root cause of several probe scripts (and would have been the
   root cause of a broken driver) reporting zero attack events.

3. ``current.yourIndex`` is NOT fixed for the lifetime of a search. Each
   ``search_step`` call answers a decision for *whichever* player must act
   next, and ``current.yourIndex`` flips between 0 and 1 turn to turn to tell
   you which player's perspective the returned ``select`` represents. A
   driver must recompute ``your_index``/``opp_index`` fresh from
   ``state.current.yourIndex`` on every single step -- caching it from the
   first observation (as the pre-existing test harness did) silently reads
   the wrong player's board every other turn.

4. Status conditions (poisoned/burned/asleep/paralyzed/confused) live on
   ``PlayerState`` (i.e. ``current.players[i].poisoned`` etc.) and describe
   that player's ACTIVE Pokemon. They are not fields on the ``Pokemon``
   object itself (there is no ``Pokemon.sleep`` / ``Pokemon.poison`` -- those
   attribute names never existed on the dataclass, which is why code that
   read them via ``hasattr`` guards always silently fell through to a
   hard-coded default).

5. Weakness/resistance math keys off the ATTACKING POKEMON's own printed
   type (``CardData.energyType``), not the type of energy spent to pay for
   the attack. ``CardData.weakness``/``CardData.resistance`` on the
   defending Pokemon are ``EnergyType`` values (or ``None``).

6. ``Option.type`` (an ``OptionType``) is the only reliable way to identify
   what kind of action an option represents. ``Option.area`` is an
   ``AreaType`` (deck/hand/discard/active/bench/prize/...), which has no
   ATTACK/RETREAT/SUPPORTER members at all -- code that compared
   ``option.area == 'ATTACK'`` (a string!) could never match anything.
"""

import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
# See the comment at the top of test_engine_mechanics.py: data/ must be on
# sys.path so the vendored engine imports under its canonical module identity
# "cg", never as "data.cg".
for _p in (str(_ROOT), str(_ROOT / "src"), str(_ROOT / "data")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from cg.api import (  # noqa: E402
    search_begin, search_step, search_release,
    to_observation_class, all_card_data, all_attack,
    SelectType, OptionType,
)

CARDS_BY_ID = {c.cardId: c for c in all_card_data()}
ATTACKS_BY_ID = {a.attackId: a for a in all_attack()}

REPLAY_DIR = _ROOT / "data" / "replays"

# Attacks whose printed text unconditionally (no coin flip) inflicts a status
# condition. Used to bias the driver toward surfacing status-effect events.
STATUS_ATTACK_IDS = {
    a.attackId
    for a in ATTACKS_BY_ID.values()
    if a.text and "Flip" not in a.text
    and any(kw in a.text for kw in ("now Poisoned", "now Asleep", "now Paralyzed", "now Confused", "now Burned"))
}


def replay_files():
    """All replay files available to mine, sorted for determinism."""
    if not REPLAY_DIR.exists():
        return []
    return sorted(REPLAY_DIR.glob("*.json"))


def find_mid_game_obs(replay):
    """Extract a real MAIN-phase (select.type == 0) observation, turn >= 1."""
    for step in replay.get("steps", []):
        if not isinstance(step, list) or len(step) < 2:
            continue
        for player_view in step[:2]:
            if not isinstance(player_view, dict):
                continue
            obs = player_view.get("observation")
            if obs is None:
                continue
            sel = obs.get("select")
            if sel is not None and sel.get("type") == 0 and (obs.get("current") or {}).get("turn", 0) >= 1:
                return obs
    return None


def load_deck(path):
    with open(path) as f:
        return [int(line.strip()) for line in f if line.strip()][:60]


TROLLEY_DECK = load_deck(_ROOT / "decks" / "trolley.csv")


def begin_from_replay(obs_dict, your_deck=None, opp_deck=None):
    """Start a real search from a replay-derived observation.

    Per the module docstring, the deck arguments only matter for information
    not already fixed by the replay snapshot; passing the (real, legal)
    trolley deck by default is just a safe placeholder.
    """
    your_deck = your_deck if your_deck is not None else TROLLEY_DECK
    opp_deck = opp_deck if opp_deck is not None else TROLLEY_DECK
    obs_class = to_observation_class(obs_dict)
    cur = obs_class.current
    yi, oi = cur.yourIndex, 1 - cur.yourIndex
    root = search_begin(
        obs_class,
        your_deck=your_deck,
        your_prize=[3] * max(len(cur.players[yi].prize), 6),
        opponent_deck=opp_deck,
        opponent_prize=[3] * max(len(cur.players[oi].prize), 6),
        opponent_hand=[3] * cur.players[oi].handCount,
        opponent_active=[],
    )
    return root.searchId, root.observation


def default_policy(select, me):
    """Choose option indices for the current select.

    For non-MAIN selects (sub-selects: CARD/COUNT/YES_NO/...), take the
    minimum legal count of leading options -- this is a generic, always-legal
    default (verified against many real games; see docstring point 1).

    For MAIN selects, prefer (in order): a guaranteed status-inflicting
    attack, any attack, evolving, attaching energy, playing a card, then
    anything that is not END. Returns None if the select is a genuine
    deadlock (0 options -- a rare, real engine state; see
    docs/rules_as_implemented.md).
    """
    if select.type != SelectType.MAIN:
        if len(select.option) == 0:
            return None
        min_count = max(select.minCount, 1) if select.minCount > 0 else 1
        return list(range(min(min_count, len(select.option))))

    if len(select.option) == 0:
        return None

    for i, opt in enumerate(select.option):
        if opt.type == OptionType.ATTACK and opt.attackId in STATUS_ATTACK_IDS:
            return [i]
    for want in (OptionType.ATTACK, OptionType.EVOLVE, OptionType.ATTACH, OptionType.PLAY):
        for i, opt in enumerate(select.option):
            if opt.type == want:
                return [i]
    non_end = [i for i, opt in enumerate(select.option) if opt.type != OptionType.END]
    if non_end:
        return [non_end[0]]
    return [0]


def find_option(select, option_type, predicate=None):
    """Return the index of the first option matching option_type (and predicate)."""
    if select is None:
        return None
    for i, opt in enumerate(select.option):
        if opt.type == option_type and (predicate is None or predicate(opt)):
            return i
    return None


class Driver:
    """Steps a real search forward, always tracking (search_id, yourIndex) correctly."""

    def __init__(self, search_id, observation):
        self.search_id = search_id
        self.observation = observation

    @classmethod
    def from_replay(cls, obs_dict, your_deck=None, opp_deck=None):
        sid, obs = begin_from_replay(obs_dict, your_deck, opp_deck)
        return cls(sid, obs)

    @property
    def current(self):
        return self.observation.current if self.observation else None

    @property
    def select(self):
        return self.observation.select if self.observation else None

    @property
    def game_over(self):
        return self.observation is None or self.observation.select is None

    def perspective(self):
        """Return (my_index, opp_index, me, opp) for the CURRENT decision.

        Recomputed fresh every call -- see module docstring point 3.
        """
        cur = self.current
        yi = cur.yourIndex
        oi = 1 - yi
        return yi, oi, cur.players[yi], cur.players[oi]

    def step(self, indices):
        new_state = search_step(self.search_id, indices)
        self.search_id = new_state.searchId
        self.observation = new_state.observation
        return self.observation

    def advance(self, policy=default_policy):
        """Take one step using `policy`. Returns False if the game ended or deadlocked."""
        if self.game_over:
            return False
        _, _, me, _ = self.perspective()
        indices = policy(self.select, me)
        if indices is None:
            return False
        self.step(indices)
        return True

    def release(self):
        if self.search_id is not None:
            try:
                search_release(self.search_id)
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Corpus mining: drive many real replay-derived games forward with
# `default_policy` and harvest concrete, naturally-occurring evidence for
# each mechanic. Characterized once (see docstring above): trolley/trolley
# decks are passed to search_begin but are cosmetic -- the real replay board
# always wins -- so this scan naturally samples whatever real decks the 1029
# recorded matches contain. A single pass typically completes in well under a
# minute (see docs/rules_as_implemented.md for the measured evidence used to
# write these assertions).
# ---------------------------------------------------------------------------

import time as _time  # noqa: E402


def mine_corpus(max_games=350, max_steps_per_game=150, time_budget_s=90, targets=None):
    """Drive many real games forward, harvesting evidence for every mechanic.

    Args:
        max_games: cap on number of replay files to seed games from.
        max_steps_per_game: cap on driver steps per game.
        time_budget_s: wall-clock cap for the whole scan.
        targets: optional dict of {category: min_count} to stop early once
            every listed category has at least that many samples.

    Returns a dict of category name -> list of evidence dicts.
    """
    targets = targets or {}

    evidence = {
        "attack_events": [],       # clean (no-text-effect) attacks: base/dmg/weak/resist
        "ko_events": [],           # KO attacks, with prize count a few steps later
        "retreat_events": [],
        "supporter_events": [],
        "evolve_events": [],
        "attack_once_per_turn": [],
        "energy_gating": [],       # (energy_count, attack_available)
        "attack_cost_gating": [],  # {cost, energy, offered} per specific attack the active Pokemon knows
        "retreat_gating": [],      # {energy, retreat_cost, retreat_present, bench_nonempty}
        "attacker_energy_types": [],  # {attacker, attacker_own_type, attached_types} at moment of attack
        "energy_attached_resets": [],  # (turn_before, flag_before, turn_after, flag_after)
        "status_transitions": {"poisoned": [], "asleep": [], "paralyzed": [], "confused": [], "burned": []},
        "sleep_wake": [],          # (replay, turn asleep became False after being True)
        "subselects": {},          # select.type(int) -> list of (context, n_options, minCount, maxCount)
        "turn_sequences": [],      # list of turn-number sequences (one list per game)
        "game_ends": [],           # (final my_prizes, final opp_prizes, reason)
    }

    def enough():
        if not targets:
            return False
        return all(len(evidence.get(cat, [])) >= n for cat, n in targets.items())

    t0 = _time.time()
    for rf in replay_files()[:max_games]:
        if _time.time() - t0 > time_budget_s or enough():
            break
        with open(rf) as f:
            try:
                replay = json.load(f)
            except Exception:
                continue
        obs_dict = find_mid_game_obs(replay)
        if obs_dict is None:
            continue
        try:
            drv = Driver.from_replay(obs_dict)
        except Exception:
            continue

        prev_status = {}
        prev_asleep_true_turn = {}
        turn_seq = []
        pending_ko = []  # list of dicts awaiting a later prize re-check
        prev_supporter_state = None  # (turn, supporterPlayed) for same-player continuity
        prev_energy_attached = {}  # player_index -> (turn, flag)

        for step in range(max_steps_per_game):
            if drv.game_over:
                cur = drv.current
                if cur is not None:
                    p0, p1 = cur.players[0], cur.players[1]
                    evidence["game_ends"].append({
                        "replay": rf.name,
                        "prizes": (len(p0.prize), len(p1.prize)),
                        "result": cur.result,
                    })
                break

            sel = drv.select
            yi, oi, me, opp = drv.perspective()
            turn_seq.append(drv.current.turn)

            evidence["subselects"].setdefault(int(sel.type), [])
            if len(evidence["subselects"][int(sel.type)]) < 8:
                evidence["subselects"][int(sel.type)].append(
                    (int(sel.context), len(sel.option), sel.minCount, sel.maxCount)
                )

            for label, flag in (("poisoned", me.poisoned), ("asleep", me.asleep),
                                 ("paralyzed", me.paralyzed), ("confused", me.confused),
                                 ("burned", me.burned)):
                key = (yi, label)
                was = prev_status.get(key, False)
                if flag and not was:
                    evidence["status_transitions"][label].append({"replay": rf.name, "turn": drv.current.turn})
                if label == "asleep":
                    if flag:
                        prev_asleep_true_turn[yi] = drv.current.turn
                    elif was and yi in prev_asleep_true_turn:
                        evidence["sleep_wake"].append({
                            "replay": rf.name,
                            "asleep_turn": prev_asleep_true_turn[yi],
                            "wake_turn": drv.current.turn,
                        })
                        del prev_asleep_true_turn[yi]
                prev_status[key] = flag

            key = ("energyAttached", yi)
            prev = prev_energy_attached.get(key)
            cur_flag = drv.current.energyAttached
            if prev is not None and prev[0] != drv.current.turn:
                evidence["energy_attached_resets"].append({
                    "turn_before": prev[0], "flag_before": prev[1],
                    "turn_after": drv.current.turn, "flag_after": cur_flag,
                })
            prev_energy_attached[key] = (drv.current.turn, cur_flag)

            # settle any pending KO prize checks once we're back to that player's turn
            still_pending = []
            for pend in pending_ko:
                if yi == pend["player_index"] and drv.current.turn > pend["turn"]:
                    pend["prize_after"] = len(me.prize)
                    evidence["ko_events"].append(pend)
                else:
                    still_pending.append(pend)
            pending_ko = still_pending

            if sel.type == SelectType.MAIN:
                my_active = me.active[0] if me.active else None
                atk_present = any(o.type == OptionType.ATTACK for o in sel.option)
                if my_active is not None:
                    evidence["energy_gating"].append((len(my_active.energies), atk_present))
                    my_card = CARDS_BY_ID.get(my_active.id)
                    if my_card is not None and my_card.attacks:
                        offered_attack_ids = {o.attackId for o in sel.option if o.type == OptionType.ATTACK}
                        energy_count = len(my_active.energies)
                        for atk_id in my_card.attacks:
                            atk_data = ATTACKS_BY_ID.get(atk_id)
                            if atk_data is None:
                                continue
                            evidence["attack_cost_gating"].append({
                                "cost": len(atk_data.energies), "energy": energy_count,
                                "offered": atk_id in offered_attack_ids,
                            })
                    if my_card is not None and my_card.retreatCost is not None:
                        ret_present = any(o.type == OptionType.RETREAT for o in sel.option)
                        bench_nonempty = bool(me.bench)
                        evidence["retreat_gating"].append({
                            "energy": len(my_active.energies), "retreat_cost": my_card.retreatCost,
                            "retreat_present": ret_present, "bench_nonempty": bench_nonempty,
                        })

                # attack-once-per-turn: does ATTACK vanish after being used, same turn?
                atk_idx = find_option(sel, OptionType.ATTACK)
                if atk_idx is not None:
                    defender = opp.active[0] if opp.active else None
                    if defender is not None:
                        hp_before = defender.hp
                        def_card = CARDS_BY_ID.get(defender.id)
                        attacker_card = CARDS_BY_ID.get(my_active.id) if my_active else None
                        attack_id = sel.option[atk_idx].attackId
                        atk_data = ATTACKS_BY_ID.get(attack_id)
                        turn_before = drv.current.turn
                        my_prizes_before = len(me.prize)
                        energy_types_attached = sorted(set(int(e) for e in my_active.energies)) if my_active else []
                        evidence["attacker_energy_types"].append({
                            "attacker": attacker_card.name if attacker_card else None,
                            "attacker_own_type": (int(attacker_card.energyType)
                                                   if attacker_card and attacker_card.energyType is not None else None),
                            "attached_types": energy_types_attached,
                        })
                        drv.step([atk_idx])
                        opp_after = drv.current.players[oi]
                        me_after = drv.current.players[yi]
                        hp_after = opp_after.active[0].hp if (opp_after.active and opp_after.active[0]) else 0
                        # once-per-turn enforcement: does attacking end the turn outright,
                        # or does the same turn continue without ATTACK being offered again?
                        turn_after = drv.current.turn
                        still_has_attack = (
                            drv.select is not None and drv.select.type == SelectType.MAIN
                            and any(o.type == OptionType.ATTACK for o in drv.select.option)
                        )
                        evidence["attack_once_per_turn"].append({
                            "turn_before": turn_before, "turn_after": turn_after,
                            "same_turn_continues": turn_after == turn_before,
                            "has_attack_after": still_has_attack,
                        })
                        if attacker_card and def_card and atk_data and not atk_data.text:
                            dmg = hp_before - hp_after
                            if dmg > 0:
                                atype = int(attacker_card.energyType) if attacker_card.energyType is not None else None
                                ev = {
                                    "attacker": attacker_card.name, "defender": def_card.name, "atype": atype,
                                    "weak": def_card.weakness, "resist": def_card.resistance,
                                    "base": atk_data.damage, "dmg": dmg,
                                    "hp_before": hp_before, "hp_after": hp_after,
                                    "defender_id": defender.id,
                                    "defender_ex": bool(def_card.ex),
                                    "defender_mega_ex": bool(def_card.megaEx),
                                }
                                evidence["attack_events"].append(ev)
                                if hp_before > 0 and hp_after <= 0:
                                    ev = dict(ev, player_index=yi, turn=turn_before, prize_before=my_prizes_before)
                                    pending_ko.append(ev)
                        continue

                ret_idx = find_option(sel, OptionType.RETREAT)
                if ret_idx is not None and my_active is not None:
                    bench_before = len(me.bench) if me.bench else 0
                    serial_before = my_active.serial
                    energy_before = len(my_active.energies)
                    drv.step([ret_idx])
                    # Retreating first opens a follow-up sub-select (e.g. SelectType.ENERGY,
                    # context DISCARD_ENERGY, choosing which attached energy pays the retreat
                    # cost) -- the active/bench swap is not reflected until that resolves.
                    # Resolve any immediate sub-selects for the SAME player before reading
                    # the "after" state.
                    guard = 0
                    while (not drv.game_over and drv.select.type != SelectType.MAIN
                           and drv.current.yourIndex == yi and guard < 5):
                        if not drv.advance():
                            break
                        guard += 1
                    me_after = drv.current.players[yi] if not drv.game_over else None
                    active_after = me_after.active[0] if (me_after and me_after.active) else None
                    evidence["retreat_events"].append({
                        "bench_before": bench_before,
                        "bench_after": len(me_after.bench) if (me_after and me_after.bench) else 0,
                        "serial_before": serial_before,
                        "serial_after": active_after.serial if active_after else None,
                        "energy_before": energy_before,
                    })
                    continue

                play_idx = None
                if me.hand:
                    for i, opt in enumerate(sel.option):
                        if opt.type == OptionType.PLAY and opt.index is not None and opt.index < len(me.hand):
                            hand_card = CARDS_BY_ID.get(me.hand[opt.index].id)
                            if hand_card is not None and int(hand_card.cardType) == 3:  # SUPPORTER
                                play_idx = i
                                break
                if play_idx is not None:
                    before = drv.current.supporterPlayed
                    turn_before = drv.current.turn
                    drv.step([play_idx])
                    still_has_supporter = (
                        drv.select is not None and drv.select.type == SelectType.MAIN
                        and find_option(drv.select, OptionType.PLAY,
                                        lambda o: (drv.current.players[yi].hand and o.index is not None
                                                   and o.index < len(drv.current.players[yi].hand)
                                                   and CARDS_BY_ID.get(drv.current.players[yi].hand[o.index].id)
                                                   and int(CARDS_BY_ID[drv.current.players[yi].hand[o.index].id].cardType) == 3)) is not None
                    )
                    evidence["supporter_events"].append({
                        "before": before, "after": drv.current.supporterPlayed,
                        "turn_before": turn_before, "turn_after": drv.current.turn,
                        "still_offered_same_turn": still_has_supporter and drv.current.turn == turn_before,
                    })
                    continue

                evo_idx = find_option(sel, OptionType.EVOLVE)
                if evo_idx is not None and my_active is not None:
                    pre_id, pre_serial = my_active.id, my_active.serial
                    turn_before = drv.current.turn
                    evolved_slot = (sel.option[evo_idx].inPlayArea, sel.option[evo_idx].inPlayIndex)
                    drv.step([evo_idx])
                    me_after = drv.current.players[yi]
                    post_active = me_after.active[0] if me_after.active else None
                    # Was the SAME board slot (identified by inPlayArea/inPlayIndex, e.g.
                    # ACTIVE slot 0) offered an EVOLVE option again in the same turn?
                    same_slot_evolve_again = (
                        drv.current.turn == turn_before
                        and drv.select is not None and drv.select.type == SelectType.MAIN
                        and find_option(drv.select, OptionType.EVOLVE,
                                        lambda o: (o.inPlayArea, o.inPlayIndex) == evolved_slot) is not None
                    )
                    evidence["evolve_events"].append({
                        "pre_id": pre_id, "post_id": post_active.id if post_active else None,
                        "pre_serial": pre_serial, "post_serial": post_active.serial if post_active else None,
                        "pre_evolution_chain": list(post_active.preEvolution) if (post_active and post_active.preEvolution) else [],
                        "turn_before": turn_before, "turn_after": drv.current.turn,
                        "evolved_slot": evolved_slot,
                        "same_slot_evolve_again_same_turn": same_slot_evolve_again,
                    })
                    continue

            if not drv.advance():
                break
        evidence["turn_sequences"].append(turn_seq)
        drv.release()

    return evidence
